### ISSUE TITLE
charmap' codec can't decode byte 0x9d 

### ISSUE THREAD

**Issue by ahbutler6064** [dwalker-uk/iTunesToSonos#1]
When I run this code against an exported playlist from iTunes 12.12.9.4 that contains only one song, I get the error in the PyCharm debugger 

Traceback (most recent call last):
  File "C:\Users\Aaron\Desktop\Playlist stuff\main.py", line 132, in <module>
    main()
  File "C:\Users\Aaron\Desktop\Playlist stuff\main.py", line 63, in main
    playlist_lines = playlist_file.readlines()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    **return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 30: character maps to <undefined>**
Exporting Test Playlist...

I have attached the source playlist.m3u8.
[Test.zip](https://github.com/dwalker-uk/iTunesToSonos/files/11594183/Test.zip)

**Comment by ahbutler6064** [comment]
Fixed the Charmap issue by changing the playlist open line as follows:
 playlist_file = open(os.path.join(settings['playlist_path'], playlist), errors='replace', encoding="utf-8")

Also, the .wpl playlist that is generated has a broken UNC path with Media/ in front of the correct UNC path.  Removed that from the .wpl path creation statement as follows:

playlist_path = unicodedata.normalize('NFC', f'{artist_album_track}').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')

And finally added rudimentary runtime exception logging as follows:

import logging
import sys
import traceback

logger = logging.getLogger('logger')
fh = logging.FileHandler('error.log')
logger.addHandler(fh)
def exc_handler(exctype, value, tb):
    logger.exception(''.join(traceback.format_exception(exctype, value, tb)))
sys.excepthook = exc_handler

Attached updated file.

[main-ErrorCheck-UTF8-FixedMediaUNC.zip](https://github.com/dwalker-uk/iTunesToSonos/files/11618101/main-ErrorCheck-UTF8-FixedMediaUNC.zip)
